version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/action-surefire-report"
      - "/block-commits"
      - "/github-app-token"
      - "/slash-command-dispatch"
    schedule:
      interval: "monthly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
