name: "link-workflow-action"
description: "Adds a comment linking back to a workflow run"
inputs:
  pull_request_number:
    description: "Number of the pull request"
    required: true
  run_id:
    description: "ID of the workflow run to link to in the PR comment"
    required: true
  github_token:
    description: "GitHub token to authenticate with"
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      id: link-workflow
      if: ${{ always() }}
      env:
        number: ${{ inputs.pull_request_number }}
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const { data: run } = await octokit.rest.actions.getWorkflowRun({
            ...context.repo,
            run_id: ${{ inputs.run_id }},
            exclude_pull_requests: true
          });
          const { data: result } = await github.rest.issues.createComment({
            ...context.repo,
            issue_number: process.env.number,
            body: 'Workflow run with all tests: ' + run.html_url
          });
          return result;
